name: test the project
on: [push] 
  # push:
  #   paths:
  #     - '**.go'
  #     - 'go.mod'
  #     - 'go.sum'
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: nix-cache
        env:
          cache-name: nix-store
        with:
          path: /tmp/nix-cache
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: cachix/install-nix-action@v18

      - name: "Import nix store cache"
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: "nix copy --from /tmp/nix-cache ./#devShells.x86_64-linux"

      - name: run test
        run: nix develop --command go test ./...

      - name: Export nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix copy --to /tmp/nix-cache ./#devShells.x86_64-linux"
