name: test the project
on: [push]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: modify /nix/store before cache
        run: |
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix
      - uses: actions/cache@v3
        env:
          cache-name: nix-store
        with:
          path: |
            /nix/store
            /nix/var/db
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: run test
        run: nix develop --command go test ./...
